import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Provider } from "@/components/ui/provider";
import Logo from "@/components/Logo";
import BottomMenu from "@/components/BottomMenu";
import { LoadingProvider } from "@/app/providers/LoadingProvider";
import { AuthContextProvider} from "./providers/AuthContext";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  
  
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased flex`}
      >
        <div className="relative w-[412px] h-[915px] !m-auto !border-1 !border-gray-600 bg-gray-950">
          <Provider>
            <AuthContextProvider>
              <LoadingProvider>
                <Logo />
                {children}
                 <BottomMenu />                 
              </LoadingProvider>
            </AuthContextProvider>
          </Provider>
        </div>
      </body>
    </html>
  );
}
